spring:
  application:
    name: "24-Welcome-API"

  boot:
    admin:
      client:
        url: "http://localhost:9090/"
        
  management:
    endpoint:
      web:
        exposure:
          include: "*"
                  
 
